#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate the compact shared footer snippet for factory-generated pages.

Single source of truth: data/content-taxonomy.json. Every link in the
snippet is derived from the taxonomy (parent hubs + topic index). Nothing
is hard-coded here, so regenerating after a taxonomy change is enough.

Output: _snippets/footer-compact.html (an underscore directory, excluded
from the Jekyll build → never deployed on its own). consumers:
  - scripts/js/factory.mjs embeds it into every child topic hub and the
    topic index (cam-nang/chu-de/*.html);
  - scripts/inject_compact_footer.py embeds it into published articles;
  - docs/ARTICLE-RULES.md requires new articles to embed the same file.
"""

import io
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TAXONOMY = os.path.join(ROOT, "data", "content-taxonomy.json")
OUT = os.path.join(ROOT, "_snippets", "footer-compact.html")

BOOK_SVG = (
    '<svg width="18" height="18" viewBox="0 0 24 24" fill="none" '
    'stroke="currentColor" stroke-width="2" stroke-linecap="round" '
    'stroke-linejoin="round" aria-hidden="true">'
    '<path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"></path>'
    '<path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z">'
    '</path></svg>'
)

STYLE = (
    ".site-footer-compact{max-width:860px;margin:40px auto 0;"
    "padding:20px 16px 36px;border-top:1px solid #2c2c2e;"
    "font-family:system-ui,-apple-system,sans-serif;color:#f5f5f7;"
    "background:transparent}"
    ".sfc-heading{display:flex;align-items:center;gap:8px;"
    "font-size:1.02rem;font-weight:800;margin:0 0 12px}"
    ".sfc-links{list-style:none;display:grid;"
    "grid-template-columns:repeat(3,1fr);gap:6px 14px;padding:0;margin:0 0 12px}"
    "@media (max-width:560px){.sfc-links{grid-template-columns:repeat(2,1fr)}}"
    ".sfc-links a{color:#aeaeb2;text-decoration:none;font-size:.92rem;"
    "font-weight:600;line-height:1.9}"
    ".sfc-links a:hover,.sfc-links a:focus-visible{color:#ff6b00}"
    ".sfc-all{color:#409cff;text-decoration:none;font-size:.92rem;"
    "font-weight:700}"
    ".sfc-all:hover,.sfc-all:focus-visible{text-decoration:underline}"
)


def build_snippet(tax):
    parents = tax.get("parents") or []
    if len(parents) != 6:
        raise SystemExit("taxonomy must have exactly 6 parents, got %d"
                         % len(parents))
    items = []
    for parent in parents:
        hub = (parent.get("parent_hub") or "").strip()
        title = (parent.get("parent_title") or "").strip()
        if not hub.startswith("/shop/") or not title:
            raise SystemExit("bad parent row: %r" % parent)
        items.append('<li><a href="%s">%s</a></li>'
                     % (hub, title.replace("&", "&amp;")
                                  .replace("<", "&lt;")))
    return (
        "<!-- COMPACT FOOTER — generated by "
        "scripts/build_footer_snippet.py from data/content-taxonomy.json. "
        "Do not edit by hand; regenerate instead. -->\n"
        '<footer class="site-footer-compact" role="contentinfo">\n'
        "<style>\n%s\n</style>\n"
        '<div class="sfc-heading">%s<span>Cẩm nang</span></div>\n'
        '<ul class="sfc-links">\n%s\n</ul>\n'
        '<a class="sfc-all" href="/shop/cam-nang/chu-de/">'
        "Xem tất cả chủ đề →</a>\n"
        "</footer>\n"
        % (STYLE, BOOK_SVG, "\n".join(items))
    )


def main():
    with io.open(TAXONOMY, encoding="utf-8") as f:
        tax = json.load(f)
    snippet = build_snippet(tax)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with io.open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(snippet)
    print("wrote %s (%d bytes, %d hub links)"
          % (os.path.relpath(OUT, ROOT), len(snippet.encode("utf-8")), 6))
    return 0


if __name__ == "__main__":
    sys.exit(main())
