#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Embed the compact shared footer into existing published article pages.

One-shot, idempotent, content-preserving: the ONLY change made to an
article file is inserting the generated footer snippet between </main> and
the canonical chatbot embed. Article body, title/meta/canonical/schema are
untouched. Rows whose status is not PUBLISHED are never modified.

The snippet itself comes from _snippets/footer-compact.html, generated by
scripts/build_footer_snippet.py from data/content-taxonomy.json.
"""

import csv
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MATRIX = os.path.join(ROOT, "data", "content-matrix.csv")
SNIPPET = os.path.join(ROOT, "_snippets", "footer-compact.html")
MARKER = "site-footer-compact"
CHATBOT_COMMENT = "<!-- CANONICAL CHATBOT EMBED"


def main():
    with io.open(SNIPPET, encoding="utf-8") as f:
        snippet = f.read()
    if MARKER not in snippet or "Xem tất cả chủ đề" not in snippet:
        print("refused: snippet missing or malformed; run "
              "scripts/build_footer_snippet.py first")
        return 2
    with io.open(MATRIX, encoding="utf-8", newline="") as f:
        rows = [r for r in csv.DictReader(f)
                if not r["article_id"].startswith("SAMPLE")]
    published = [r for r in rows
                 if (r.get("status") or "").strip() == "PUBLISHED"
                 and (r.get("output_path") or "").strip()]
    changed, skipped = [], []
    for r in published:
        path = os.path.join(ROOT, r["output_path"].strip().lstrip("/"))
        if not os.path.isfile(path):
            print("ERROR: PUBLISHED row without file: %s" % r["output_path"])
            return 3
        with io.open(path, encoding="utf-8") as f:
            src = f.read()
        if MARKER in src:
            skipped.append(r["article_id"])
            continue
        if CHATBOT_COMMENT in src:
            new = src.replace(CHATBOT_COMMENT, snippet + CHATBOT_COMMENT, 1)
        elif "</body>" in src:
            new = src.replace("</body>", snippet + "</body>", 1)
        else:
            print("ERROR: no insertion point in %s" % r["output_path"])
            return 3
        if MARKER not in new:
            print("ERROR: insertion failed for %s" % r["output_path"])
            return 3
        with io.open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(new)
        changed.append(r["article_id"])
    print("articles updated: %d, already had footer: %d, published total: %d"
          % (len(changed), len(skipped), len(published)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
